name: Build

on:
  push:
    branches: [fork]
  pull_request:
    branches: [fork]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Install
        run: yarn --no-progress --non-interactive --no-lockfile
      - name: Build
        run: yarn build
