name: Build

on:
  push:
    branches: [fork_cra5]
  pull_request:
    branches: [fork_cra5]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16.x
          cache: 'npm'
      - name: Install npm@8
        run: npm i -g npm@8
      - name: Install
        run: npm ci --prefer-offline
      - name: Build
        run: npm run build
