name: Build BRS

on:
  push:
    branches: [fork]
  pull_request:
    branches: [fork]

defaults:
  run:
    shell: bash -l {0}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16.x

      - name: Run e2e
        run: |
          tasks/e2e-brs.sh
