name: fork_cra5-release

on:
  push:
    branches: [fork_cra5]

defaults:
  run:
    shell: bash -l {0}

jobs:
  ReleaseWeb:
    name: Release dev version to NPM
    runs-on: ubuntu-latest
    environment: Publishing
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4
        with:
          ref: fork_cra5

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16.x

      - name: Install
        run: npm ci --prefer-offline

      - name: Build react-error-overlay
        run: |
          cd packages/react-error-overlay/
          npm run build:prod

      - name: Build
        run: npm run build

      - name: Publish NPM package
        run: |
          cd packages/react-scripts
          npm version prerelease --preid=dev --no-git-tag-version
          npm publish --tag alpha
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
