name: Lint

on:
  push:
    branches: [fork]
  pull_request:
    branches: [fork]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14.x

      - name: Install
        run: yarn --no-progress --non-interactive --no-lockfile

      - name: Alex
        run: yarn alex
