name: Lint

on:
  push:
    branches: [fork_cra5]
  pull_request:
    branches: [fork_cra5]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16.x

      - name: Install npm@8
        run: npm i -g npm@8
      - name: Install
        run: npm ci --prefer-offline
      - name: Alex
        run: npm run alex
